### ISSUE TITLE
could not find function "summarySE"

### ISSUE THREAD

**Issue by oushujun** [vicruiser/tukey_test_plot#2]
\> significance<-tukey_plot_significance(data_example)
>Using X as id variables
Error in summarySE(data_melted, measurevar = "value", groupvars = c("X",  : 
  could not find function "summarySE"
In addition: Warning message:
In melt(data) :
  The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(data). In the next version, this warning will become an error

**Comment by vicruiser** [comment]
Hi, 
try loading your data with read.table() instead of fread(). Or to convert the data.table to data.frame prior to use the melt function. It seems that reshape2::melt has some problem with data.table.

**Comment by oushujun** [comment]
I think I found the problem. There is a list of dependencies in the `turkey_function.R` script:
>library(ggplot2)
library(grid)
library(fBasics)
library(tidyr)
library(reshape2)
library(agricolae)
library(Rmisc)
library(gdata)
library(rlist)
library(string)

Installing all these will solve my issue. Thanks!
